name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build the Docker image Server
      run: docker build . --file docker/thoth-server/Dockerfile --tag gaborando/thoth-server:latest
  
    - name: Push Docker image Server
      run: docker push gaborando/thoth-server:latest
      
    - name: Build the Docker image Web
      run: docker build . --file docker/thoth-web/Dockerfile --tag gaborando/thoth-web:latest
      
    - name: Push Docker image Web
      run: docker push gaborando/thoth-web:latest
